version: 1.3.{build}
image: Visual Studio 2017 RC
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  VisualStudioVersion: 15
build_script:
- cmd: >-
    set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%


    git submodule update --init --recursive


    nuget restore

    msbuild
after_test:
- cmd: >-
    nuget pack %appveyor_project_name%.Core/%appveyor_project_name%.Core.csproj -version %appveyor_build_version%  -Symbols

    nuget pack %appveyor_project_name%/%appveyor_project_name%.csproj -version %appveyor_build_version% -Symbols

    nuget pack %appveyor_project_name%.Templates/%appveyor_project_name%.Templates.csproj -version %appveyor_build_version% -Symbols
artifacts:
- path: '*.nupkg'
deploy:
- provider: Environment
  name: Nuget.org
  on:
    branch: master
